openapi: 3.0.3
info:
  title: Tic-tac-toe API
  version: 0.0.0
  description: A simple API that lets registered users play Tic-tac-toe against each
    other.
paths:
  /games/:
    get:
      operationId: games_list
      parameters:
      - in: query
        name: after
        schema:
          type: string
          format: date-time
      - in: query
        name: before
        schema:
          type: string
          format: date-time
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - in: query
        name: status
        schema:
          type: string
          enum:
          - finished
          - open
          - progress
      tags:
      - games
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedGameList'
          description: ''
    post:
      operationId: games_create
      description: Create a new open game with the current user as the first player.
      tags:
      - games
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: ''
  /games/{id}/:
    get:
      operationId: games_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this game.
        required: true
      tags:
      - games
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: ''
  /games/{id}/join/:
    post:
      operationId: games_join_create
      description: Join an open game as the second player.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this game.
        required: true
      tags:
      - games
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /games/{id}/move/:
    post:
      operationId: games_move_create
      description: Make a move. Row and column indices are zero-based.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this game.
        required: true
      tags:
      - games
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MakeMove'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MakeMove'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MakeMove'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /login/:
    post:
      operationId: login_create
      description: |-
        Log in the user. The returned token must be used in all requests to authenticated endpoints in
        the Authentication HTTP header with the "Bearer" prefix.

        e.g. <code>Authorization: Bearer 5f6f928c76b99aeb78d5f17d97336747898b3103</code>
      tags:
      - login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginInput'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LoginInput'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginOutput'
          description: ''
  /logout/:
    post:
      operationId: logout_create
      description: Log out the user and revoke the current token.
      tags:
      - logout
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /openapi/:
    get:
      operationId: openapi_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - openapi
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /register/:
    post:
      operationId: register_create
      description: Create a new user with the given username and password.
      tags:
      - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterInput'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegisterInput'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegisterInput'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /users/:
    get:
      operationId: users_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - users
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserList'
          description: ''
  /users/{id}/:
    get:
      operationId: users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        board:
          type: array
          items:
            type: array
            items:
              type: integer
          readOnly: true
        winner:
          $ref: '#/components/schemas/ReducedUser'
        first_player:
          $ref: '#/components/schemas/ReducedUser'
        second_player:
          $ref: '#/components/schemas/ReducedUser'
        created:
          type: string
          format: date-time
          readOnly: true
        status:
          allOf:
          - $ref: '#/components/schemas/StatusEnum'
          readOnly: true
      required:
      - board
      - created
      - first_player
      - id
      - second_player
      - status
      - winner
    LoginInput:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - password
      - username
    LoginOutput:
      type: object
      properties:
        token:
          type: string
        username:
          type: string
        id:
          type: integer
      required:
      - id
      - token
      - username
    MakeMove:
      type: object
      properties:
        row:
          type: integer
          maximum: 2
          minimum: 0
        col:
          type: integer
          maximum: 2
          minimum: 0
      required:
      - col
      - row
    PaginatedGameList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Game'
    PaginatedUserList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/User'
    ReducedUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
      required:
      - id
      - username
    RegisterInput:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - password
      - username
    StatusEnum:
      enum:
      - open
      - progress
      - finished
      type: string
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
        game_count:
          type: integer
        win_rate:
          type: number
          format: double
      required:
      - game_count
      - id
      - username
      - win_rate
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
